import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  loginPage: { flexGrow: 1, justifyContent: 'center', width: '100%', maxWidth: 540, alignSelf: 'center', padding: 24 },
  loginCard: { backgroundColor: '#fffdf5', padding: 24, borderRadius: 24, marginTop: 30 },
  formHelp: { color: '#65716a', lineHeight: 21, marginTop: 10, marginBottom: 20 },
  fieldLabel: { color: '#203a33', fontWeight: '700', fontSize: 13, marginBottom: 8 },
  input: { borderWidth: 1, borderColor: '#cbd6cd', backgroundColor: '#fff', borderRadius: 10, padding: 14, fontSize: 16, marginBottom: 18, color: '#183b36' },
  errorText: { color: '#a42c28', marginBottom: 18, lineHeight: 21 },
  logoutError: { color: '#ffbf87', marginTop: 12 },
  accountRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12, flexWrap: 'wrap', marginBottom: 22 },
  detailLink: { color: '#1d5d50', fontWeight: '700', marginTop: 12 },
  detailPage: { flex: 1, backgroundColor: '#f5f4ef' },
  detailBody: { width: '100%', maxWidth: 840, alignSelf: 'center', padding: 24, gap: 16 },
  detailPoster: { width: 120, height: 180, borderRadius: 14, backgroundColor: '#e8eee3' },
  movieHero: { flexDirection: 'row', alignItems: 'center', marginBottom: 12 },
  movieTitle: { fontSize: 24, lineHeight: 30, fontWeight: '800', color: '#183b36', marginBottom: 12 },
  synopsis: { color: '#52645a', fontSize: 15, lineHeight: 25, marginBottom: 12 },
  infoBlock: { backgroundColor: '#fff', padding: 16, borderRadius: 12, borderWidth: 1, borderColor: '#e5e8df' },
  container: { flex: 1, backgroundColor: '#142b2b' },
  header: { width: '100%', maxWidth: 840, alignSelf: 'center', paddingHorizontal: 24, paddingTop: 20, paddingBottom: 28 },
  brandRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 24 },
  brandMark: { width: 30, height: 30, borderRadius: 9, backgroundColor: '#b9e879', alignItems: 'center', justifyContent: 'center', marginRight: 10 },
  brandIcon: { fontSize: 13, color: '#142b2b' },
  brand: { color: '#dce9df', fontSize: 11, fontWeight: '700', letterSpacing: 2 },
  heading: { color: '#fffdf5', fontSize: 34, fontWeight: '800', letterSpacing: -1, marginBottom: 8 },
  subtitle: { color: '#b8c9c4', fontSize: 15, lineHeight: 22 },
  badge: { flexDirection: 'row', alignItems: 'center', alignSelf: 'flex-start', backgroundColor: '#263e3c', paddingHorizontal: 12, paddingVertical: 8, borderRadius: 20, marginTop: 20 },
  statusDot: { width: 7, height: 7, borderRadius: 4, backgroundColor: '#b9e879', marginRight: 8 },
  statusError: { backgroundColor: '#ffbf87' },
  badgeText: { color: '#e3eadf', fontSize: 12 },
  content: { flex: 1, backgroundColor: '#f5f4ef', borderTopLeftRadius: 26, borderTopRightRadius: 26, overflow: 'hidden' },
  centered: { flexGrow: 1, alignItems: 'center', justifyContent: 'center', padding: 28, width: '100%', maxWidth: 560, alignSelf: 'center' },
  stateTitle: { color: '#183b36', fontSize: 21, fontWeight: '700', textAlign: 'center' },
  message: { textAlign: 'center', marginVertical: 18, color: '#65716a', fontSize: 15, lineHeight: 23 },
  button: { backgroundColor: '#1d5d50', borderRadius: 12, paddingHorizontal: 24, paddingVertical: 14 },
  buttonPressed: { opacity: 0.75 },
  buttonText: { color: '#fff', fontSize: 14, fontWeight: '700' },
  list: { width: '100%', maxWidth: 840, alignSelf: 'center', paddingHorizontal: 18, paddingBottom: 24 },
  sectionHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', flexWrap: 'wrap', gap: 8, paddingVertical: 24 },
  sectionTitle: { fontSize: 21, fontWeight: '700', color: '#203a33' },
  sectionLabel: { fontSize: 10, letterSpacing: 1.5, color: '#667568', fontWeight: '700' },
  card: { flexDirection: 'row', backgroundColor: '#fff', borderRadius: 18, padding: 14, marginBottom: 14, borderWidth: 1, borderColor: '#e5e8df' },
  poster: { width: 90, height: 135, borderRadius: 10, backgroundColor: '#edf0e7' },
  placeholder: { alignItems: 'center', justifyContent: 'center', backgroundColor: '#e8eee3' },
  placeholderIcon: { fontSize: 28, color: '#82977e', marginBottom: 6 },
  placeholderText: { color: '#65765f', fontSize: 11 },
  details: { flex: 1, marginLeft: 14 },
  cardLabel: { fontSize: 9, fontWeight: '700', letterSpacing: 1.4, color: '#718164', marginTop: 3, marginBottom: 7 },
  title: { fontSize: 18, lineHeight: 23, fontWeight: '700', marginBottom: 8, color: '#183b36' },
  description: { fontSize: 13, lineHeight: 20, color: '#64716b' },
});
